### ISSUE TITLE
Capilization and grammar

### ISSUE THREAD

**Issue by davids-tips** [davids-tips/Davids-tips.github.io#16]
List files here that need to be revised in the comments using your GitHub account and I will Correct them here

**Comment by narel151** [comment]
some of the damage types in the d6 table under the ring of elemental chaos aren't capitalized
Ill look through the rest of the pages to see if theres anything else

**Comment by narel151** [comment]
the damage types that aren't capitalized are lightning and poison

**Comment by davids-tips** [comment]
Please open the page and copy the link to the page that is messed up
@narel151

**Comment by narel151** [comment]
https://davids-tips.github.io/HTML/roe/ec.html

**Comment by narel151** [comment]
in addition, the words "strength" is misspelled once and "damage" is misspelled three times on the page for "Arm of the Fire Genasi Veteran"

**Comment by narel151** [comment]
The word "Avenger" should be capitalized when referring to the class on its page, the section describing "Shift Judgement (Also on the Avenger class page) should have a period at the end of its description, and this may or may not be intentional, but the last section of description is called "Nobile Duel". I don't know whether this is intentional.

**Comment by narel151** [comment]
Nothing wrong in blade step, as far as I can see

**Comment by davids-tips** [comment]
Please Create indivigual issues per page including link in the top bar for easy access
